[package]
name = "kira"
version = "0.2.0"
authors = ["Andrew Minnich <aminnich3@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Dynamic audio library for games"
repository = "https://github.com/tesselode/kira"
keywords = ["gamedev", "audio", "music"]
categories = ["game-development", "multimedia::audio"]
readme = "../readme.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
benchmarking = []
mp3 = ["minimp3"]
ogg = ["lewton"]
flac = ["claxon"]
wav = ["hound"]
default = ["mp3", "ogg", "flac", "wav"]

[dependencies]
claxon = { version = "0.4.3", optional = true }
cpal = { version = "0.13.1", features = ["wasm-bindgen"] }
indexmap = "1.6.0"
hound = { version = "3.4.0", optional = true }
lewton = { version = "0.10.1", optional = true }
minimp3 = { version = "0.5.0", optional = true }
nanorand = "0.5.1"
ringbuf = "0.2.2"
