[package]
name = "kira-cpal"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.13.3"
kira = { path = "../kira" }
ringbuf = "0.2.3"
