[package]
name = "kira-ogg"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kira = { path = "../kira" }
lewton = "0.10.1"
