name: Clippy

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: install cpal dependencies
        run: sudo apt-get install libasound2-dev
      - name: install wasm32 target
        run: rustup target add wasm32-unknown-unknown
      - name: clippy (desktop - no features)
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -p kira --no-default-features
          name: desktop - no features
      - name: clippy (desktop - with cpal feature)
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -p kira --no-default-features --features=cpal
          name: desktop - with cpal feature
      - name: clippy (desktop - with mp3 feature)
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -p kira --no-default-features --features=mp3
          name: desktop - with mp3 feature
      - name: clippy (desktop - with all features)
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -p kira --all-features
          name: desktop - with all features
      - name: clippy (wasm32 - no features)
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -p kira --no-default-features --target=wasm32-unknown-unknown
          name: wasm32 - no features
      - name: clippy (wasm32 - with cpal feature)
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -p kira --no-default-features --features=cpal --target=wasm32-unknown-unknown
          name: wasm32 - with cpal feature
      - name: clippy (wasm32 - with mp3 feature)
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -p kira --no-default-features --features=mp3 --target=wasm32-unknown-unknown
          name: wasm32 - with mp3 feature
      - name: clippy (wasm32 - with all features)
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -p kira --all-features
          name: wasm32 - with all features
